### POST login
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "testuser@example.com",
  "password": "test1234"
}

###
### Получить всех работников
GET http://localhost:8080/api/admin/workers
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0dXNlckBleGFtcGxlLmNvbSIsImlhdCI6MTc1MDY5MDIzOCwiZXhwIjoxNzUwNzc2NjM4fQ.UIc67F-PgNH-lVet0Xc_xnQ2Q4LCJ9LNbuLZbf1GGqA
###

### Получить работников по роли
GET http://localhost:8080/api/admin/workers/role/DRIVER
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0dXNlckBleGFtcGxlLmNvbSIsImlhdCI6MTc1MDY5MDIzOCwiZXhwIjoxNzUwNzc2NjM4fQ.UIc67F-PgNH-lVet0Xc_xnQ2Q4LCJ9LNbuLZbf1GGqA


###

### Поиск работников
GET http://localhost:8080/api/admin/workers/search?query=User
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0dXNlckBleGFtcGxlLmNvbSIsImlhdCI6MTc1MDY5MDIzOCwiZXhwIjoxNzUwNzc2NjM4fQ.UIc67F-PgNH-lVet0Xc_xnQ2Q4LCJ9LNbuLZbf1GGqA

###

### Получить работника по ID
GET http://localhost:8080/api/admin/workers/2
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0dXNlckBleGFtcGxlLmNvbSIsImlhdCI6MTc1MDY5MDIzOCwiZXhwIjoxNzUwNzc2NjM4fQ.UIc67F-PgNH-lVet0Xc_xnQ2Q4LCJ9LNbuLZbf1GGqA

###

### Добавить нового работника
POST http://localhost:8080/api/admin/workers
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0dXNlckBleGFtcGxlLmNvbSIsImlhdCI6MTc1MDY5MDIzOCwiZXhwIjoxNzUwNzc2NjM4fQ.UIc67F-PgNH-lVet0Xc_xnQ2Q4LCJ9LNbuLZbf1GGqA
Content-Type: application/json

{
  "email": "nikita7@gmail.com",
  "password": "Wardotforme1!",
  "firstName": "Nikita",
  "lastName": "Tolstykh",
  "phone": "+48732558254",
  "role": "DRIVER"
}

###

### Обновить работника
PUT http://localhost:8080/api/admin/workers/2
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0dXNlckBleGFtcGxlLmNvbSIsImlhdCI6MTc1MDY5MDIzOCwiZXhwIjoxNzUwNzc2NjM4fQ.UIc67F-PgNH-lVet0Xc_xnQ2Q4LCJ9LNbuLZbf1GGqA
Content-Type: application/json

{
  "email": "nikita76@gmail.com",
  "password": "uiyhihihi",
  "firstName": "Nikitay",
  "lastName": "Tolstykh",
  "phone": "+48721558254",
  "role": "DRIVER"
}



### Удалить работника
DELETE http://localhost:8080/api/admin/workers/4
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0dXNlckBleGFtcGxlLmNvbSIsImlhdCI6MTc1MDY5MDIzOCwiZXhwIjoxNzUwNzc2NjM4fQ.UIc67F-PgNH-lVet0Xc_xnQ2Q4LCJ9LNbuLZbf1GGqA

###

### Получить все машины
GET http://localhost:8080/api/admin/vehicles
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0dXNlckBleGFtcGxlLmNvbSIsImlhdCI6MTc1MDY5MDIzOCwiZXhwIjoxNzUwNzc2NjM4fQ.UIc67F-PgNH-lVet0Xc_xnQ2Q4LCJ9LNbuLZbf1GGqA

###

### Получить машину по ID
GET http://localhost:8080/api/admin/vehicles/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0dXNlckBleGFtcGxlLmNvbSIsImlhdCI6MTc1MDY5MDIzOCwiZXhwIjoxNzUwNzc2NjM4fQ.UIc67F-PgNH-lVet0Xc_xnQ2Q4LCJ9LNbuLZbf1GGqA

###

### Добавить машину
POST http://localhost:8080/api/admin/vehicles
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0dXNlckBleGFtcGxlLmNvbSIsImlhdCI6MTc1MDY5MDIzOCwiZXhwIjoxNzUwNzc2NjM4fQ.UIc67F-PgNH-lVet0Xc_xnQ2Q4LCJ9LNbuLZbf1GGqA
Content-Type: application/json

{
  "brand": "Toyota",
  "model": "Corolla",
  "color": "White",
  "licensePlate": "ABC123",
  "comment": "New car",
  "driverId": 3
}

###

### Обновить машину
PUT http://localhost:8080/api/admin/vehicles/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0dXNlckBleGFtcGxlLmNvbSIsImlhdCI6MTc1MDY5MDIzOCwiZXhwIjoxNzUwNzc2NjM4fQ.UIc67F-PgNH-lVet0Xc_xnQ2Q4LCJ9LNbuLZbf1GGqA
Content-Type: application/json

{
  "brand": "Toyota",
  "model": "Camry",
  "color": "Black",
  "licensePlate": "ABC123",
  "comment": "Updated comment",
  "driverId": 6
}

###

### Удалить машину
DELETE http://localhost:8080/api/admin/vehicles/5
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0dXNlckBleGFtcGxlLmNvbSIsImlhdCI6MTc1MDY5MDIzOCwiZXhwIjoxNzUwNzc2NjM4fQ.UIc67F-PgNH-lVet0Xc_xnQ2Q4LCJ9LNbuLZbf1GGqA
