### GET all orders
GET http://localhost:8080/api/client/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuaWtpdGF0b2xzdHloN0BnbWFpbC5jb20iLCJpYXQiOjE3NTE0MDM2NTAsImV4cCI6MTc1MTQ5MDA1MH0.vxhhO4s1Q8e1uxFq53apCz3JhHPX84zo7Avu-F9cHyo

### GET order details
GET http://localhost:8080/api/client/orders/8
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuaWtpdGF0b2xzdHloN0BnbWFpbC5jb20iLCJpYXQiOjE3NTE0MDM2NTAsImV4cCI6MTc1MTQ5MDA1MH0.vxhhO4s1Q8e1uxFq53apCz3JhHPX84zo7Avu-F9cHyo

### POST create order
POST http://localhost:8080/api/client/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuaWtpdGF0b2xzdHloN0BnbWFpbC5jb20iLCJpYXQiOjE3NTE0MDM2NTAsImV4cCI6MTc1MTQ5MDA1MH0.vxhhO4s1Q8e1uxFq53apCz3JhHPX84zo7Avu-F9cHyo
Content-Type: application/json

{
  "fromAddress": "ул. 40л. Победы, 12",
  "toAddress": "ул.Новокузнецкая 15",
  "cargoType": "Документы",
  "cargoDescription": "Бумаги ценные",
  "weightKg": 5,
  "comment": "Доставить в срочном порядке",
  "distanceCategory": "LONG",
  "paymentMethod": "CASH",
  "pickupTime": "2025-07-01T12:00:00"
}

### GET list available orders to rate
GET http://localhost:8080/api/client/orders/available-for-rating
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuaWtpdGF0b2xzdHloN0BnbWFpbC5jb20iLCJpYXQiOjE3NTE0MDM2NTAsImV4cCI6MTc1MTQ5MDA1MH0.vxhhO4s1Q8e1uxFq53apCz3JhHPX84zo7Avu-F9cHyo


### POST rate order
POST http://localhost:8080/api/client/orders/8/rating
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuaWtpdGF0b2xzdHloN0BnbWFpbC5jb20iLCJpYXQiOjE3NTE0MDM2NTAsImV4cCI6MTc1MTQ5MDA1MH0.vxhhO4s1Q8e1uxFq53apCz3JhHPX84zo7Avu-F9cHyo
Content-Type: application/json

{
"stars": 4,
  "comment": "very good"
}