### GET all orders
GET http://localhost:8080/api/client/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuaWtpdGF0b2xzdHloN0BnbWFpbC5jb20iLCJpYXQiOjE3NTExMzc5ODksImV4cCI6MTc1MTIyNDM4OX0.HT6cB0uwcKupomRLBcB-gsWeyQs50DiAmWDRM_XMKX8

### GET order details
GET http://localhost:8080/api/client/orders/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuaWtpdGF0b2xzdHloN0BnbWFpbC5jb20iLCJpYXQiOjE3NTExMzc5ODksImV4cCI6MTc1MTIyNDM4OX0.HT6cB0uwcKupomRLBcB-gsWeyQs50DiAmWDRM_XMKX8

### POST create order
POST http://localhost:8080/api/client/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuaWtpdGF0b2xzdHloN0BnbWFpbC5jb20iLCJpYXQiOjE3NTExMzc5ODksImV4cCI6MTc1MTIyNDM4OX0.HT6cB0uwcKupomRLBcB-gsWeyQs50DiAmWDRM_XMKX8
Content-Type: application/json

{
  "fromAddress": "ул. Гагарина, 12",
  "toAddress": "ул.Новокузнецкая 15",
  "cargoType": "Электроника",
  "cargoDescription": "Ноутбуки",
  "weightKg": 30,
  "comment": "Осторожно, хрупкое",
  "distanceCategory": "LONG",
  "paymentMethod": "CASH",
  "pickupTime": "2025-07-01T12:00:00"
}

###