### POST register
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "email": "nikitatolstyh7@gmail.com",
  "password": "test1234",
  "firstName": "Nikita",
  "lastName": "Tolstykh",
  "phone": "+48732558254",
  "role": "CLIENT"
}

### GET login
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "nikita1@gmail.com",
  "password": "111111"
}

### GET login
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "nik@mail.com",
  "password": "111111"
}

