### GET all orders
GET http://localhost:8080/api/client/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuaWtpdGF0b2xzdHloN0BnbWFpbC5jb20iLCJpYXQiOjE3NTE5MjA5NDEsImV4cCI6MTc1MjAwNzM0MX0.zgrML5Ag03iTW3O6MdiR3gcVLuYQxlD2UR0X7zfa5eo

### GET order details
GET http://localhost:8080/api/client/orders/10
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuaWtpdGF0b2xzdHloN0BnbWFpbC5jb20iLCJpYXQiOjE3NTE5MjA5NDEsImV4cCI6MTc1MjAwNzM0MX0.zgrML5Ag03iTW3O6MdiR3gcVLuYQxlD2UR0X7zfa5eo

### POST create order
POST http://localhost:8080/api/client/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuaWtpdGF0b2xzdHloN0BnbWFpbC5jb20iLCJpYXQiOjE3NTE5MjA5NDEsImV4cCI6MTc1MjAwNzM0MX0.zgrML5Ag03iTW3O6MdiR3gcVLuYQxlD2UR0X7zfa5eo
Content-Type: application/json

{
  "fromAddress": "ul. Zlota 44,Warszawa",
  "toAddress": "ul.Daleka 6S/1, Grodzisk Mazowiecki",
  "cargoType": "Elektronika",
  "cargoDescription": "Komputer",
  "weightKg": 20,
  "comment": "",
  "distanceCategory": "LONG",
  "paymentMethod": "CASH",
  "pickupTime": "2025-07-09T12:00:00"
}

### GET list available orders to rate
GET http://localhost:8080/api/client/orders/available-for-rating
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuaWtpdGF0b2xzdHloN0BnbWFpbC5jb20iLCJpYXQiOjE3NTE5MjA5NDEsImV4cCI6MTc1MjAwNzM0MX0.zgrML5Ag03iTW3O6MdiR3gcVLuYQxlD2UR0X7zfa5eo


### POST rate order
POST http://localhost:8080/api/client/orders/10/rating
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuaWtpdGF0b2xzdHloN0BnbWFpbC5jb20iLCJpYXQiOjE3NTE5MjA5NDEsImV4cCI6MTc1MjAwNzM0MX0.zgrML5Ag03iTW3O6MdiR3gcVLuYQxlD2UR0X7zfa5eo
Content-Type: application/json

{
"stars": 5,
  "comment": "Bardzo dobrze, grzeczny kierowca i extra serwis"
}

### GET order status history
GET http://localhost:8080/api/client/orders/10/status-history
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuaWtpdGF0b2xzdHloN0BnbWFpbC5jb20iLCJpYXQiOjE3NTE5MjA5NDEsImV4cCI6MTc1MjAwNzM0MX0.zgrML5Ag03iTW3O6MdiR3gcVLuYQxlD2UR0X7zfa5eo


###GET client statistics
GET http://localhost:8080/api/client/orders/statistics
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuaWtpdGF0b2xzdHloN0BnbWFpbC5jb20iLCJpYXQiOjE3NTE5MjA5NDEsImV4cCI6MTc1MjAwNzM0MX0.zgrML5Ag03iTW3O6MdiR3gcVLuYQxlD2UR0X7zfa5eo
