### GET all orders
GET http://localhost:8080/api/client/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuaWtpdGF0b2xzdHloN0BnbWFpbC5jb20iLCJpYXQiOjE3NTE0OTI4NzksImV4cCI6MTc1MTU3OTI3OX0.I4IHvDQF60zhnZG4Hk6ljpUsREX7xaKUmCflr2g1HM0

### GET order details
GET http://localhost:8080/api/client/orders/10
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuaWtpdGF0b2xzdHloN0BnbWFpbC5jb20iLCJpYXQiOjE3NTE0OTI4NzksImV4cCI6MTc1MTU3OTI3OX0.I4IHvDQF60zhnZG4Hk6ljpUsREX7xaKUmCflr2g1HM0

### POST create order
POST http://localhost:8080/api/client/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuaWtpdGF0b2xzdHloN0BnbWFpbC5jb20iLCJpYXQiOjE3NTE0OTI4NzksImV4cCI6MTc1MTU3OTI3OX0.I4IHvDQF60zhnZG4Hk6ljpUsREX7xaKUmCflr2g1HM0
Content-Type: application/json

{
  "fromAddress": "ул. Daleka 6s/1,Grodzisk Mazowiecki",
  "toAddress": "Towarowa 22, Warszawa",
  "cargoType": "Elektronika",
  "cargoDescription": "Komputer",
  "weightKg": 10,
  "comment": "",
  "distanceCategory": "MEDIUM",
  "paymentMethod": "CASH",
  "pickupTime": "2025-07-04T12:00:00"
}

### GET list available orders to rate
GET http://localhost:8080/api/client/orders/available-for-rating
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuaWtpdGF0b2xzdHloN0BnbWFpbC5jb20iLCJpYXQiOjE3NTE0OTI4NzksImV4cCI6MTc1MTU3OTI3OX0.I4IHvDQF60zhnZG4Hk6ljpUsREX7xaKUmCflr2g1HM0


### POST rate order
POST http://localhost:8080/api/client/orders/10/rating
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuaWtpdGF0b2xzdHloN0BnbWFpbC5jb20iLCJpYXQiOjE3NTE0OTI4NzksImV4cCI6MTc1MTU3OTI3OX0.I4IHvDQF60zhnZG4Hk6ljpUsREX7xaKUmCflr2g1HM0
Content-Type: application/json

{
"stars": 5,
  "comment": "Bardzo dobrze, grzeczny kierowca i extra serwis"
}

### GET order status history
GET http://localhost:8080/api/client/orders/10/status-history
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuaWtpdGF0b2xzdHloN0BnbWFpbC5jb20iLCJpYXQiOjE3NTE0OTI4NzksImV4cCI6MTc1MTU3OTI3OX0.I4IHvDQF60zhnZG4Hk6ljpUsREX7xaKUmCflr2g1HM0
