### GET all orders
GET http://localhost:8080/api/client/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuaWtpdGF0b2xzdHloN0BnbWFpbC5jb20iLCJpYXQiOjE3NTMzNTkyMzYsImV4cCI6MTc1MzQ0NTYzNn0.k9zAWuvx-LjCrU7MHKEbE22ELoK61LSydfJo_B8EuQQ
### GET order details
GET http://localhost:8080/api/client/orders/10
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuaWtpdGF0b2xzdHloN0BnbWFpbC5jb20iLCJpYXQiOjE3NTIxNzgxOTcsImV4cCI6MTc1MjI2NDU5N30.Ge0kGl9FftFlEqyPKPRSurRazHGXGpf3hHrlvHtUUEI

### POST create order
POST http://localhost:8080/api/client/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuaWtpdGF0b2xzdHloN0BnbWFpbC5jb20iLCJpYXQiOjE3NTIxNzgxOTcsImV4cCI6MTc1MjI2NDU5N30.Ge0kGl9FftFlEqyPKPRSurRazHGXGpf3hHrlvHtUUEI
Content-Type: application/json

{
  "fromAddress": "ul. blabla 44,Warszawa",
  "toAddress": "ul.Daleka 6S5/1, Grodzisk Mazowiecki",
  "cargoType": "Elektroniczno",
  "cargoDescription": "Komputericzno",
  "weightKg": 20,
  "comment": "",
  "distanceCategory": "LONG",
  "paymentMethod": "CARD",
  "pickupTime": "2025-07-13T12:00:00"
}

### GET list available orders to rate
GET http://localhost:8080/api/client/orders/available-for-rating
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuaWtpdGF0b2xzdHloN0BnbWFpbC5jb20iLCJpYXQiOjE3NTIxNzgxOTcsImV4cCI6MTc1MjI2NDU5N30.Ge0kGl9FftFlEqyPKPRSurRazHGXGpf3hHrlvHtUUEI


### POST rate order
POST http://localhost:8080/api/client/orders/17/rating
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuaWtpdGF0b2xzdHloN0BnbWFpbC5jb20iLCJpYXQiOjE3NTMzNTkyMzYsImV4cCI6MTc1MzQ0NTYzNn0.k9zAWuvx-LjCrU7MHKEbE22ELoK61LSydfJo_B8EuQQ
Content-Type: application/json

{
"stars": 2,
  "comment": "Bardzo dobrze, grzeczny kierowca i extra serwis"
}

### GET order status history
GET http://localhost:8080/api/client/orders/10/status-history
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuaWtpdGF0b2xzdHloN0BnbWFpbC5jb20iLCJpYXQiOjE3NTIxNzgxOTcsImV4cCI6MTc1MjI2NDU5N30.Ge0kGl9FftFlEqyPKPRSurRazHGXGpf3hHrlvHtUUEI


###GET client statistics
GET http://localhost:8080/api/client/orders/statistics
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuaWtpdGF0b2xzdHloN0BnbWFpbC5jb20iLCJpYXQiOjE3NTMzNTkyMzYsImV4cCI6MTc1MzQ0NTYzNn0.k9zAWuvx-LjCrU7MHKEbE22ELoK61LSydfJo_B8EuQQ
