### Получить все заказы
GET http://localhost:8080/api/dispatcher/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuaWtpdGExQGdtYWlsLmNvbSIsImlhdCI6MTc1MjE4MTQ1OSwiZXhwIjoxNzUyMjY3ODU5fQ.Ago2X4PPe2YCr7pUubfIiEjVpcUqk6MrrshTIDA_hZk

###

### Получить детали заказа
GET http://localhost:8080/api/dispatcher/orders/8
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuaWtpdGExQGdtYWlsLmNvbSIsImlhdCI6MTc1MjE4MTQ1OSwiZXhwIjoxNzUyMjY3ODU5fQ.Ago2X4PPe2YCr7pUubfIiEjVpcUqk6MrrshTIDA_hZk

###

### Получить доступных водителей
GET http://localhost:8080/api/dispatcher/available-drivers
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuaWtpdGExQGdtYWlsLmNvbSIsImlhdCI6MTc1MjE4MTQ1OSwiZXhwIjoxNzUyMjY3ODU5fQ.Ago2X4PPe2YCr7pUubfIiEjVpcUqk6MrrshTIDA_hZk

###

### Назначить водителя на заказ
POST http://localhost:8080/api/dispatcher/orders/13/assign-driver
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuaWtpdGExQGdtYWlsLmNvbSIsImlhdCI6MTc1MjE4MTQ1OSwiZXhwIjoxNzUyMjY3ODU5fQ.Ago2X4PPe2YCr7pUubfIiEjVpcUqk6MrrshTIDA_hZk
Content-Type: application/json

{
  "driverId": 11
}

###

### Обновить статус заказа
PATCH http://localhost:8080/api/dispatcher/orders/12/status
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuaWtpdGExQGdtYWlsLmNvbSIsImlhdCI6MTc1MjE4MTQ1OSwiZXhwIjoxNzUyMjY3ODU5fQ.Ago2X4PPe2YCr7pUubfIiEjVpcUqk6MrrshTIDA_hZk
Content-Type: application/json

{
  "status": "ASSIGNED"
}

###

### Обновить всю информацию о заказе
PUT http://localhost:8080/api/dispatcher/orders/8
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuaWtpdGExQGdtYWlsLmNvbSIsImlhdCI6MTc1MjE4MTQ1OSwiZXhwIjoxNzUyMjY3ODU5fQ.Ago2X4PPe2YCr7pUubfIiEjVpcUqk6MrrshTIDA_hZk
Content-Type: application/json

{
  "fromAddress": "г. Брест, ул. Карбышева, 21",
  "toAddress": "г. Минск, пр. Независимости, 3",
  "cargoType": "Документы",
  "cargoDescription": "Контракт",
  "weightKg": 0.5,
  "comment": "Передать в руки",
  "distanceCategory": "LONG",
  "price": 25.00,
  "paymentMethod": "CASH",
  "pickupTime": "2025-07-01T14:00:00"
}

###

### Удалить заказ
PATCH http://localhost:8080/api/dispatcher/orders/8/cancel-order
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuaWtpdGExQGdtYWlsLmNvbSIsImlhdCI6MTc1MjE4MTQ1OSwiZXhwIjoxNzUyMjY3ODU5fQ.Ago2X4PPe2YCr7pUubfIiEjVpcUqk6MrrshTIDA_hZk

### GET order status list
GET http://localhost:8080/api/dispatcher/orders/10/status-history
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuaWtpdGExQGdtYWlsLmNvbSIsImlhdCI6MTc1MjE4MTQ1OSwiZXhwIjoxNzUyMjY3ODU5fQ.Ago2X4PPe2YCr7pUubfIiEjVpcUqk6MrrshTIDA_hZk
